apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
  namespace: brewget
data:
  # Service ports
  AUTH_HTTP_PORT: "8000"
  AUTH_GRPC_PORT: "9000"
  SETTINGS_HTTP_PORT: "8002"
  EMAIL_HTTP_PORT: "8001"
  EMAIL_GRPC_PORT: "9001"

  # Service hostnames
  AUTH_HOSTNAME: "http://auth-service"
  EMAIL_HOSTNAME: "http://email-service"
  SETTINGS_HOSTNAME: "http://settings-service"
  FRONTEND_HOSTNAME: "http://brewget.brewingbytes.com"

  # CORS configuration
  CORS_URL: "http://brewget.brewingbytes.com"

  # Passkey configuration
  RP_ID: "brewget.brewingbytes.com"
  RP_ORIGIN: "https://brewget.brewingbytes.com"
  RP_NAME: "BrewGet"
