on:
  pull_request:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - main

name: Rust Checker
jobs:
  linter:
    runs-on: ubuntu-latest
    name: Rust Lint
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: changes
        name: Changes
        with:
          filters: |
            backend:
              - '.github/workflows/rust.yml'
              - 'backend/auth-service/**'
              - 'backend/email-service/**'
              - 'backend/settings-service/**'
              - 'backend/proto/**'
              - 'backend/Cargo.lock'
              - 'backend/Cargo'
              - 'backend/rust-toolchain.toml'
      - name: Cache
        if: steps.changes.outputs.backend == 'true'
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Prerequisites
        if: steps.changes.outputs.backend == 'true'
        run: |
          sudo apt update
          sudo apt install protobuf-compiler
      - name: Clippy
        if: steps.changes.outputs.backend == 'true'
        run: cargo clippy --all-features --workspace -- -D warnings
      - name: Format
        if: steps.changes.outputs.backend == 'true'
        run: cargo fmt --all --check

  tester:
    runs-on: ubuntu-latest
    name: Rust Test
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: changes
        name: Changes
        with:
          filters: |
            backend:
              - '.github/workflows/rust.yml'
              - 'backend/auth-service/**'
              - 'backend/email-service/**'
              - 'backend/settings-service/**'
              - 'backend/proto/**'
              - 'backend/Cargo.lock'
              - 'backend/Cargo'
              - 'backend/rust-toolchain.toml'
      - name: Cache
        if: steps.changes.outputs.backend == 'true'
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Prerequisites
        if: steps.changes.outputs.backend == 'true'
        run: |
          sudo apt update
          sudo apt install protobuf-compiler
      - name: Test
        if: steps.changes.outputs.backend == 'true'
        run: cargo test

  builder:
    runs-on: ubuntu-latest
    name: Rust Build
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: changes
        name: Changes
        with:
          filters: |
            backend:
              - '.github/workflows/rust.yml'
              - 'backend/auth-service/**'
              - 'backend/email-service/**'
              - 'backend/settings-service/**'
              - 'backend/proto/**'
              - 'backend/Cargo.lock'
              - 'backend/Cargo'
              - 'backend/rust-toolchain.toml'
      - name: Cache
        if: steps.changes.outputs.backend == 'true'
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Prerequisites
        if: steps.changes.outputs.backend == 'true'
        run: |
          sudo apt update
          sudo apt install protobuf-compiler
      - name: Build
        if: steps.changes.outputs.backend == 'true'
        run: cargo build
